{
 "title": "socks",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Default", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Connections | Active",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "target": "alias(transformNull(stats.gauges.socks.connections.active), 'Active')"
    }
   ]
  },
  {
   "title": "Received | 24h",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "target": "alias(movingSum(stats_counts.socks.traffic.bytes_received, '24h'), 'Received')"
    }
   ]
  },
  {
   "title": "Sent | 24h",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "target": "alias(movingSum(stats_counts.socks.traffic.bytes_sent, '24h'), 'Sent')"
    }
   ]
  },
  {
   "title": "Unauthorized IP | 24h",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "movingSum(stats_counts.socks.errors.unauthorized_ip, '24h')"
    }
   ]
  },
  {
   "title": "DNS Entries",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "stats.gauges.socks.dns.cache.entries"
    }
   ]
  },
  {
   "title": "Error Rate | 24h",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "target": "aliasByNode(movingSum(exclude(stats_counts.socks.errors.*, 'unauthorized_ip'), '24h'), 3)"
    }
   ]
  },
  { "title": "DNS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Resolve",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "alias(transformNull(stats.timers.socks.dns.resolve.time.mean), 'Resolve')"
    }
   ]
  },
  {
   "title": "Miss Rate | 24h",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "target": "alias(asPercent(movingAverage(stats_counts.socks.dns.cache.misses, '24h'), movingAverage(sum(stats_counts.socks.dns.cache.{hits,misses}), '24h')), 'Miss Rate')"
    }
   ]
  },
  { "title": "Timing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Connection",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "alias(transformNull(stats.timers.socks.connections.duration.mean), 'Duration')"
    }
   ]
  },
  {
   "title": "Target Dial",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "alias(transformNull(stats.timers.socks.connections.target_dial_duration.mean), 'Duration')"
    }
   ]
  }
 ]
}